# -*- coding: utf-8 -*-
"""Assignment_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yksecwniC8f_7eikTH2c2RFUr5idPj8o

1 st Problem - Accept Two Numbers as Input and Display Greater Number
"""

num1 = int(10)
num2 = int(20)
if num2 > num1:
  print("20 is Greater Number")
else:
  print("10 is Smaller Number")

"""2 nd Problem - Accept Two Numbers as Input and Display Smaller Number"""

num1 = 10
num2 = 20
if num1 < num2:
  print("10 is Smaller Number")
else:
  print("20 is Greater Number")

"""3rd Problem - Display Greater as well as Smaller Number"""

num1 =10
num2 =20
num3 =30
num4 =70
num5 =2

max_num = max(10,20,30,70,2)
min_num = min(10,20,30,70,2)

print("The Greater Number is", max_num)
print("The Smaller Number is", min_num)

"""4th Problem -Display the Number which is the Second Highest Value"""

num1 =10
num2 =20
num3= 30
num4= 101
num5= 50

num_list = [10,20,30,101,50]
num_list.sort() # It Gives Sorted List-> 10,20,30,50,101

print("The Second Highest Number is",num_list[3])

"""5th Problem -  pick numbers between range 10 to 20 and display squares of even numbers and cubes of odd numbers.


"""

for i in range(10,21):
  if i%2 == 0:
    print(i, "Square is", i**2)
  else:
    print(i, "Cube is", i**3)

"""6th Problem - Display the Pattern

"""

for i in range(1,6):
  print(i * '*')

"""7th Problem - Display the Pattern

"""

for i in range(1,4):
  print(i * 'Hi')

"""8th Problem - Display the pattern

"""

for i in range(1,4):
  print(i * 'Hi')
for j in range(4,6):
    print(j * 'Bye')

"""9th Problem - Display the Pattern"""

for i in (1,2,3,4,5):
  if i %2 == 1:
    print('Hi'*i)
  else:
    print('Bye'*i)

"""10th Problem - Display the Pattern"""

for i in [1, 2, 3, 4, 5, 6]:
  print(i * (str(i)+' '))

"""11th Problem - Display the Pattern"""

for i in range(6, 2, -1):
    for j in range(5):
        print(i, end="")
    print()

for i in [6,5,4,3]:
  print(str(i) * 5)