# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rNYcMHMwWC4OlLm_uDTOGo-LmlUVbNip

1st Problem - Print Even Numbers Between 1 to 20
"""

for a in range(1,21):
  if a % 2 == 0: # Checks Number is Divisible by 2
    print(a)

"""2 nd Problem - Mentioned Pattern"""

for i in [1,2,3,4,5]:
  print( i * '+' )

"""3rd Problem - Mentioned Pattern"""

for i in [4,3,2,1]:
  print( i * '+' )

"""4th Problem - Mentioned Pattern"""

n = 5 # also We can Write int(input("Enter number of rows: ")) i.e taking input from User
for i in range(1,n+1):
    for j in range(1, i+1):
        print(i, end="")
    print()

"""5th Problem - program in python to print table of 10"""

for i in range(1,11):
  print(" 10* ", i ,"=", 10*i )