# -*- coding: utf-8 -*-
"""Assignment_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FKyeIVYIl1N5aHVjkiGwi3HwfGqeReG7

1. Write a program in python to check whether a number is palindrome or not ?
Example - 121 , 232,111, 151
"""

nums = 151
#nums = 191

if nums > 99 and nums < 1000:
    if int(nums/100) == nums % 10:
      print("The Given Number is Palindrome")
    else:
      print("The Given Number is not Palindrome")
else:
    print("3 Digits Numbers Only")

"""2. Write a program in python to check whether a number is even or odd. If the number is even then print the cube of the number and if the number is odd then print the square of that number.

"""

#num = 4
num = 9
if num % 2 == 0:
    print("The Given Number is Even & Hence its Cube is" , num ** 3)
else:
    print("The Given Number is Odd & Hence its Square is", num ** 2)

"""3. Write a program in python to check the number of characters in a string, if the number of characters are even then display reverse of that string , if number of character are odd then display alternate characters"""

a = 'RAM'
#a = 'KEYBOARD'

if len(a) % 2 == 0: # It Checks Whether Number of Characters are Even
  print(a[::-1]) # Selecting Characters From Right to Left i.e (Reverse)
else:
  print(a[::2]) # Selecting the Alternate Characters From Input

"""4. Implement 1st problem statement using function (UDF)

"""

def test(nums):

  if nums > 99 and nums < 1000:
      if int(nums/100) == nums % 10:
        print("The Given Number is Palindrome")
      else:
        print("The Given Number is not Palindrome")
  else:
      print("3 Digits Numbers Only")

test(121)
test(111)
test(232)
test(123)

"""5. Implement 2nd  problem statement using function (UDF)

"""

def check_nums(num):
  if num % 2 == 0:
    print("The Given Number is Even & Hence its Cube is" , num ** 3)
  else:
    print("The Given Number is Odd & Hence its Square is", num ** 2)

check_nums(2)
check_nums(5)

"""6. Implement 3rd  problem statement using function (UDF)

"""

a = input("Enter the String: ")
if len(a) % 2 == 0: # It Checks Whether Number of Characters are Even
  print(a[::-1]) # Selecting Characters From Right to Left i.e (Reverse)
else:
  print(a[::2]) # Selecting the Alternate Characters From Input