# -*- coding: utf-8 -*-
"""ClassNotes_17_18_19_22_23_24_25_26_May23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KnqBmYEQj3rwSfjAEY_yg_iL-nIozbP2

1) Write a program in python to accept two numbers as input , and display greater number among them.
"""

num1 = 20
num2 = 100
if num1 > num2:
  print(num1)
else:
  print(num2)

"""2) Write a program in python to accept one number as input , and check whether that number is even or odd"""

n = 10
if n%2 ==0:
  print('Even')
else:
  print('Odd')

a = 10.5
b = -20.0
c = 0.0
if c :
  print('Hi')
else:
  print('Bye')

a = True
b = False
if 2>3 :
  print('Hi')
else:
  print('Bye')

a = ()
b = (10,20,30)

type(b)

if b :
  print('Hi')
else:
  print('Bye')

s1 = ''
s2 = ""
s3 = 'Hi'
len(s3)

if s3:
  print('Yes')
else:
  print('No')

a = "Amit's car"

b = 'Amit"'

"""List notation [] - can be changed (mutable)
tuple notation () - can't be changed (immutable)
set notation {} - only values - doesn't allow duplicates
dict notation {} - key:value - key is like named index
"""

s = {10,20,30}
s1 = set()

type(s1)

if s1 :
  print('Hi')
else:
  print('Bye')

d = {'id':1 , 'name':'Amit'}
d1 = {}

type(d1)

if d1 :
  print('Hi')
else:
  print('Bye')

"""Assignment-01
https://docs.google.com/document/d/1j_dqUZrGTUa9yVKs3CDGPNamKtH7yx2WiS-9fPMp7ug/edit?usp=sharing
"""

x = None

if x:
  print('Hi')
else:
  print('Bye')

"""https://docs.google.com/spreadsheets/d/1xSwwYNAU78EEbdyCtS1iN7dOk77n_-SqDPxl7bMRtBk/edit?usp=sharing

18-May-23 , Datatypes and Loop
"""

marks = [90,78,81,45,98]
print(marks)  # here as we used marks withoout quotes , so marks will be considered as variable name

print('marks')  # here we passed value with quotes,so it will be considered as string

for tgeeks in marks :
  print(tgeeks+2)

marks = [90,78,81,45,98]
for i in marks:
  if i > 50:
    print(i)

marks = [90,78,81,45,98,50]
for i in marks:
  if i >= 50:
    print(i , ' above or equal to 50')
  else:
    print(i,' below 50')

marks = [90,78,81,45,98,50]
for i in marks:
  if i > 50:
    print(i , ' greater than 50')
  elif i == 50:
    print(i,' is equal to 50')
  else:
    print(i,' below 50')

5%2 == 0

60%2 == 0

n = 42
if n%2:
  print('Odd')
else:
  print('Even')

n = 42
if n%2 == 0:
  print('Even')
else:
  print('Odd')

for i in [1,2,3,4,5]:
  print(i * '+' )

for i in [5,4,3,2,1]:
  print(i * '+' )

city = 'Pune' # define string

type(city) # checked datatype

print(city[0:3]) # fetch charactes fom index number 0 to 2 (3 is stop point)

'2' + 2

2+2

for i in [1,2,3,-4,5]:
  print(i* '+' )

for i in 'Tgeeks':
  if i*2 == 'TT' or i*2 == 'kk':
    print(i,' Hi')
  else:
    print(i,' Bye')

"""Assignment-01
https://docs.google.com/document/d/1j_dqUZrGTUa9yVKs3CDGPNamKtH7yx2WiS-9fPMp7ug/edit?usp=sharing

19-May-2023 class notes
"""

for i  in [1,2,3,4,5]:
  for j in [10,20]:
    print(i*j)

for i in ['Jan', 'Feb','March']:
  for j in [1,2,3,4,5,6,7,8,9,10]:
    print(j,'-',i,'-',2023)

for i in 'City':
  print(i)

for i in ['City']:
  for j in ['City']:
    print(i+j)

for i in [1,2,3,4,5]:
  for j in '+':
    print(i*j)

employee = {'id':1      , 'name':'Amit'       ,       'age':25}

for i in employee.items():
  print(i)

s = {1,2,3,4,5}
for i in s:
  print(i)

for i in 100.5:
  print(i)

for i in 'True':
  print(i)

"""dsbyprince@gmail.com"""

a = '[]'
b = ['Amit']
c = 'Amit'

type(c)

len(c)

for num in [1,2,3,4,5]:
    print(num,end='  ')

x= int(input("enter number of rows"))
for l in range(1,x+1):
  for m in range(1,l+1):
    print(l, end="")
    print()

"""Write a program in python to print even numbers between 1 to 20

"""

list(range(2,21,2))

for i in range(1,21):
  if i%2 == 0:
    print(i)

"""Problem statement - 02"""

for i in range(1,6):
  print(i * '+')

"""Problem statement - 03"""

for i in [4,3,2,1]:
  print(i * '+')

list(range(4,0,-1))

"""Problem statement - 04"""

for i in [1,2,3,4,5]:
  print(i * str(i))

"""Problem statement - 05 : Write a program in python to print table of 10

"""

for i in range(1,11):
  for j in [10]:
    print(j,'*',i,"=",j*i)

for i in range(1,11):
  print("10 * " + str(i) + " = " , (10*i))

"10 * " + str(7)

"10 * " + str(7) + " = "

"10 * " + str(7) + " = " + str(10*7)

"""Assignment-01
https://docs.google.com/document/d/1j_dqUZrGTUa9yVKs3CDGPNamKtH7yx2WiS-9fPMp7ug/edit?usp=sharing

23-May-23 class notes [Loop]
"""

for i in range(6,5):
  print(i)

a = 1
while a < 5: # infinite loop
  print(a)

a = 1
while a < 5:
  print(a+10)

a=1
while a<6:
  print(a*'+')
  a=a+1

a=1
while a<6:
   print(a * str(a) )
   a=a+1

"""Write a program to display even numbers between 1 to 10 with the help of while loop in python"""

a=2
while a<11:
  print(a)
  a=a+2

a = 1
while a <= 10:
    if a%2 == 0:
        print(a)
    a =a+1

a= 1
while a<11:
  if a%2==0:
    print(a)
  a=a+1

for i in 500:
  print(i)

a = [10,20,30,40,70,80,92,11,'Amit']

min(a)

max(a)

"""24-May-2023 class notes"""

a = []
for i in [1,2,3,4,5]:
  for j in [1,2,3]:
    for k in [4,5,6]:
      a.append(i+j+k)

len(a)

help(a.append)

b = []

b = [2,3]

print(b)

b.append(50)

b.extend([45,46,47])

b

a = 1
b = 1
while a < 5:
  while b < 3:
    print(a+b)
    a = a+1

a = 1
b = 1
while a < 5:
  while b < 3:
    print(a+b)
    b = b+1
  a = a+1

a = 1
b = 1
while a < 5:
  while b < 3:  # This inner loop will run only once and in first run when b will become 3 , it will not allow you to rerun the same loop , because of condition
    b = b+1
  print(a+b)     # This print statement is part of outer loop , which run 4 times for a = 1,2,3,4 , so that is why you got 4 result
  a = a+1

a = 1
b = 1
while a < 7:
  while b < 3:  # This inner loop will run only once and in first run when b will become 3 , it will not allow you to rerun the same loop , because of condition
    b = b+1
  print(a+b)
  a = a+1

a = 1
b = 1
c = 5
d = 6
while a < c:
  while b < d:
    b = b+a
    print(b)
  print(a)
  a = a+1

"""25-May-23 classnotes"""

a = 1
b = 1
while a < 5:
  while b < 3:
    print(a+b)
    a = a+1

a = []
for i in [1,2]:
  for j in [1,2]:
    for k in [4,5]:
      for m in [5,6]:
        for n in [1,2]:
          a.append('Hi')
print(len(a))

2 ** 5

for i in [1,2]:
  for j in [10,20]:
      print(i,j)

for i in ['Amit','Sumit']:
  for k in [' live in India']:
    print(i,k)

"""Problem statement : we have a dict with name and age of people , and we want to identify those names , who are eligible for voting system , based on age , and condition is age >= 18 , {'Amit':18 , 'Sumit': 12}"""

for i in {'Amit':18 , 'Sumit': 12}.items():
  print(i)

a = 1    # in this code a= 1 will run only once
for i in [1,2,3]:
  while a < 5:
    print(i+a)
    a = a+1

for i in [1,2,3]:
  a = 1  # in this code , a will reset to 1 everytime when you get a new item in i from list
  while a < 5:
    print(i+a)
    a = a+1

x = 1
while x < 5:
  for j in [1,2,3]:
    print(x+j)
  x = x+1

a = 1
while a < -5:
  print(a)

a = 1
while a < 5:
  print(a)
  a = a-1

a = {'Amit':18 , 'Sumit': 12}

print(a)

print(a.keys())

"""Problem statement : we have a dict with name and age of people , and we want to identify those names , who are eligible for voting system , based on age , and condition is age >= 18 , {'Amit':18 , 'Sumit': 12}

26-may-23 classnotes
"""

a = 1
while a < 2:
  print(a)
  a = a+1

"""Problem statement : we have a dict with name and age of people , and we want to identify those names , who are eligible for voting system , based on age , and condition is age >= 18 , {'Amit':18 , 'Sumit': 12}"""

a= {'Amit':18 , 'Sumit': 12,'Allen':25}
print('Eligible Voters:')
for i, j in a.items():
  if j >= 18:
    print (i)

for i in {'age':25, 'name':'Amit', 'city':'Pune'}:
  print(i)

for i in {'age':25, 'name':'Amit', 'city':'Pune'}:
  if i != 'age':  # whether i is age or not , if not then condition is True else False
    print(i)

x = [10,20,30,40,50]
x[0:3]

x[3:]

y = ['Amit' , 'Smith' , 'Allen' , 'Kathy']  # declare y as a list

y[0:2]   # display elements from index 0 to 1 , out will be sublist

y[0:2][0]

y[0:2][1]

t = ('Amit' , 'Smith' , 'Allen' , 'Kathy')

type(t)

t[5:7]

x = t[5:7]

message = 'Hello world'

len(message)

message[0:5]

message[0:5][0:2]

message[0:5][0:2][0]

s = 'I am in India'

s[8:13]

if 'Idn' in s:
  print('Hi')
else:
  print('Bye')

a = [100,200,300,400,500,600]

a[-1]

a[-3:-1]

a[3:-1]