# -*- coding: utf-8 -*-
"""Class_ Notes- 15May2023 -Data Types- If_Else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XARZfK30uz9fpEk3yeOSTU42vqqpc2YI
"""

Marks = 50      # Defined a Variable to Store a Marks
if Marks > 35:  # Check Whether Marks > 35 or Not
  print("Student is Pass")   # Display Message
else:                        # If student didn't marks get > 35
  print("Student is Failed") # Display Message

Balance = 1000.90
if Balance <= 100:
  print("Your Balance is Insufficient")
else:
  print("Your Balance is Sufficient")

battery_level = 50
if battery_level <= 20:
  print("Low Battery,Please Charge Your Device")
else:
  print("Your Device is Charged")

a = 100
b = 20
if a > b:
  print(a)
else:
  print(b)

# Write a program in  python to accept two numbers as input and display greater number among them
a = 1000
b = 200
c = 300
if a > b and a > c:
  print(a)
if b > a and b > c:
  print(b)
if c > a and c > b:
  print(c)

a = 1000
b = 200
c = 300
if a > b and a > c:
  print(a)
elif b > a and b > c:
  print(b)
else:
  print(c)

a = 2500
b = 200
c = 300
if a > b and  a > c:
  print(a)