# -*- coding: utf-8 -*-
"""Code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kWl_Yj3Bv6R5Tn1FGkUNo8uRUFdOCBQv
"""

print("Hello World")

a = 10
b = 90.01
c = "Aniket"

print(type(b))

print(type(c))

print(c)

marks = 55
if marks>60:
  print("Congrats You are Passed!")
else:
  print("Sorry You are Failed!")

a = 75
b = 50
if a>b:
  print(a)
else:
  print(b)

number = 48
if number%2 == 0 :
  print(number,"is Even!")
else:
  print(number,"is Odd!")

marks = 90
if marks>80:
  print("Your Grade is A")
elif marks>60:
  print("Your Grade is B")
elif marks>40:
  print("Your Grade is C")
else:
  print("Your Grade is D")